# Generated by Django 2.2.10 on 2020-02-29 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Produto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sku', models.CharField(max_length=20)),
                ('descricao', models.CharField(max_length=200)),
                ('url', models.URLField()),
                ('habilitado', models.CharField(max_length=3)),
                ('buybox', models.CharField(max_length=3)),
                ('menorpreco', models.CharField(max_length=50)),
                ('loja', models.CharField(max_length=50)),
                ('site', models.CharField(max_length=50)),
            ],
        ),
    ]
